### ISSUE TITLE
Problems with the assignment of input data points to clusters

### ISSUE THREAD

**Issue by tsteenbock** [Dan-Tan/Iterative-Label-Spreading#1]
Dear Dan-Tan,

First of all, thanks for the wonderful code. It runs smoothly without any error. However, after using your code I have trouble understanding the assignment of the input data point to the output clusters of the code. My motivation is to understand which input data points belong to which cluster. In particular, I do not understand the following which makes the assignment difficult:

1) I noticed that there is a variable example_ILS.ordering in your code that contains 2999 data point if I originally submit a matrix mit 3000 data points. Is this because the point with index 0 is the same as in the original (unsorted) dataset?

2) I also struggle to understand the variable "indices", which contains as many elements as clusters found. Initially, I thought that the numbers correspond to the starting point of the clusters (first index of the ordered datapoints for a given cluster). In my example, I obtain 6 values for indices: [816, 2154, 1783, 2280, 2642]. However, I thought the values should become larger from cluster to cluster, but it isn't. I think that I misunderstand something here and I would be very happy if you could tell me how to use this variable.

I am thankful for any help!

Best,
Torben

**Comment by Dan-Tan** [comment]
Thank you for the query.

I will take a look at the code base again and get back to regarding your questions, I haven't used this in a while.

**Comment by tsteenbock** [comment]
Thank you for your help!

**Comment by Dan-Tan** [comment]
@tsteenbock 

Sorry for the slow respone. 

1. The reason there are 2999 elements in the ordering list is that the starting data point is not included in that list (I should fix this as it breaks encapsulation). So the first element of the list is the index of the data point that was labelled second (the starting data point was labelled "first").

```python
# Some dataset
X = ...
# Init clustering object
example_ILS = ILS()

# Perform label spreading starting at the 10th data point in the dataset (indx_labelled defaults 0 if not specified)
example_ILS.label_spreading(X, indx_labelled=[10])

# The ordering list will not include 10 at the beginning.
example_ILS.ordering

# If you want a list that includes an ordering for all data points use
example_ILS._first + example_ILS.ordering
```
Apologies, this was a poor design decision by me (one of many), I'll look into returning what is expected.

2.  You are correct in assuming that the returned indices from `ILS.segmentation` are the starting indices of the clusters. However keep in mind that the raw dataset given is not permuted or altered, so it is not ordered according to the ordering ILS calculates. The intuition that the starting indices should be ascending is somewhat correct and corresponds to the way in which the package calculates the starting indices.

    1. Segment the list of minimum distances (`ILS.rmin`) and the ordering according to the segmentation passed in.
    2. For each segment smooth the segment and find the index of the minimum. (**These indices would be ascending**)
    3. Convert the indices from indexing the ordered rmin list to index the unordered dataset (**No longer ascending**)

If you have any more questions feel free to ask. 

Also you have drawn my attention to a index misalignment in the `ILS.segmentation` method so thank you again. My intuition is this bug is only impactful in extreme cases as it will cause the ordered indices to be off by one however given the indices corresponded to a minimum the next indice over will likely by a close to a minimum, I will fix this.
